markdown: kramdown
kramdown:
  math_engine: mathjax

reading_time:
  second_plural: "sec"    # default: seconds
  minute_singular: "min"  # default: minute
  minute_plural: "min"    # default: minutes

url: "https://beegass.github.io/" # the base hostname & protocol for your site
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-katex